package it.unipv.ingsw.magstudio.model.bean;

/**
 * Raccolta di tutte le regioni italiane
 */
public enum Regione {
    LOMBARDIA,PIEMONTE,LIGURIA,VENETO,ABRUZZO,TOSCANA,UMBRIA,CAMPANIA,LAZIO,PUGLIA,CALABRIA,BASILICATA,SICILIA,
    SARDEGNA,FRIULI_VENEZIA_GIULIA,TRENTINO_ALTO_ADIGE,VALLE_D_AOSTA,EMILIA_ROMAGNA,MOLISE,MARCHE
}
