CREATE DATABASE IF NOT EXISTS HIVEHUB;
USE HIVEHUB;

CREATE TABLE IF NOT EXISTS PERSONA(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME_UTENTE varchar(255) NOT NULL UNIQUE,
    NOME varchar(255) NOT NULL,
    COGNOME varchar(255) NOT NULL,
    CF varchar(255) NOT NULL,
    DATA_NASCITA DATE NOT NULL,
    INDIRIZZO_NOME varchar(255) NOT NULL,
    INDIRIZZO_CIVICO varchar(10) NOT NULL,
    INDIRIZZO_CAP int NOT NULL,
    INDIRIZZO_CITTA varchar(255) NOT NULL,
    INDIRIZZO_PROVINCIA varchar(255) NOT NULL,
    INDIRIZZO_TIPO_STRADA ENUM('VIA','VIALE','PIAZZA','STRADA','VICOLO','CORSO','LARGO') NOT NULL,
    INDIRIZZO_REGIONE ENUM('LOMBARDIA', 'PIEMONTE', 'LIGURIA', 'VENETO', 'ABRUZZO', 'TOSCANA', 'UMBRIA',
			'CAMPANIA', 'LAZIO', 'PUGLIA', 'CALABRIA', 'BASILICATA', 'SICILIA', 'SARDEGNA', 'FRIULI_VENEZIA_GIULIA',
			'TRENTINO_ALTO_ADIGE', 'VALLE_D_AOSTA', 'EMILIA_ROMAGNA', 'MOLISE', 'MARCHE') NOT NULL,
    CONTATTO_EMAIL varchar(255),
    CONTATTO_TELEFONO varchar(255)
);

CREATE TABLE IF NOT EXISTS T_PERSONA(
	PASSWORD varchar(64) NOT NULL,
    ID INT PRIMARY KEY,
    FOREIGN KEY (ID) REFERENCES PERSONA(ID)
);