CREATE DATABASE IF NOT EXISTS HIVEHUB;
USE HIVEHUB;

CREATE TABLE IF NOT EXISTS PERSONA(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME_UTENTE varchar(255) NOT NULL UNIQUE,
    NOME varchar(255) NOT NULL,
    COGNOME varchar(255) NOT NULL,
    CF varchar(255) NOT NULL,
    DATA_NASCITA DATE NOT NULL,
    INDIRIZZO_NOME varchar(255) NOT NULL,
    INDIRIZZO_CIVICO varchar(10) NOT NULL,
    INDIRIZZO_CAP int NOT NULL,
    INDIRIZZO_CITTA varchar(255) NOT NULL,
    INDIRIZZO_PROVINCIA varchar(255) NOT NULL,
    INDIRIZZO_TIPO_STRADA ENUM('VIA','VIALE','PIAZZA','STRADA','VICOLO','CORSO','LARGO') NOT NULL,
    INDIRIZZO_REGIONE ENUM('LOMBARDIA', 'PIEMONTE', 'LIGURIA', 'VENETO', 'ABRUZZO', 'TOSCANA', 'UMBRIA',
			'CAMPANIA', 'LAZIO', 'PUGLIA', 'CALABRIA', 'BASILICATA', 'SICILIA', 'SARDEGNA', 'FRIULI_VENEZIA_GIULIA',
			'TRENTINO_ALTO_ADIGE', 'VALLE_D_AOSTA', 'EMILIA_ROMAGNA', 'MOLISE', 'MARCHE') NOT NULL,
    CONTATTO_EMAIL varchar(255),
    CONTATTO_TELEFONO varchar(255)
);

CREATE TABLE IF NOT EXISTS T_PERSONA(
	PASSWORD varchar(64) NOT NULL,
    ID INT PRIMARY KEY,
    FOREIGN KEY (ID) REFERENCES PERSONA(ID)
);

CREATE TABLE IF NOT EXISTS PRODOTTO(
  CODICE int NOT NULL,
  NOME varchar(255) NOT NULL,
  DESCRIZIONE varchar(255) DEFAULT NULL,
  IMMAGINE longblob,
  PRIMARY KEY (CODICE)
);

CREATE TABLE IF NOT EXISTS POSIZIONE (
  SCAFFALE int NOT NULL,
  AREA int NOT NULL,
  LIVELLO int NOT NULL,
  SCOMPARTIMENTO int NOT NULL,
  CODICE int NOT NULL,
  QNT int DEFAULT 0,

  PRIMARY KEY (SCAFFALE,AREA,LIVELLO,SCOMPARTIMENTO),
  FOREIGN KEY (CODICE) REFERENCES PRODOTTO(CODICE)
)

INSERT INTO PERSONA VALUES
(1, "ADMIN", "MARIO", "ROSSI","AAABBB00E00G388U", "1965-02-28",
"ROMA", "5/7",27028,"SAN MARTINO SICCOMARIO","PAVIA","VIA","LOMBARDIA",
"MARIO.ROSSI@GMAIL.COM", NULL);

INSERT INTO T_PERSONA VALUES
("8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918",1);